name: Purge Azure CDN

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure service principal login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name datdevstorage --auth-mode login -d '$web' -s .

    - name: Purge CDN
      run:
        az cdn endpoint purge -n ${{ secrets.AZURE_CDN_ENDPOINT }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --content-paths "/*" --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --no-wait
        
    - name: Azure service principal logout
      run: |
        az logout
